name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build and Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: bunx tsc --noEmit
      - run: bun --bun run build
